// docs/GUIDE/components/advanced-filter/advanced-filter.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  signal,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { SelectModule } from 'primeng/select';
import { AnimatedButtonComponent } from '../animated-button/animated-button.component';
import { DatePickerComponent } from '../../shared/components/date-picker/date-picker.component';

export interface FilterOption {
  label: string;
  value: string;
}

export interface FilterField {
  key: string;
  label: string;
  type: 'select' | 'date-range' | 'text' | 'trash';
  options?: FilterOption[];
  placeholder?: string;
}

export interface FilterCriteria {
  search: string;
  [key: string]: unknown;
}

@Component({
  selector: 'app-advanced-filter',
  standalone: true,
  imports: [CommonModule, FormsModule, SelectModule, AnimatedButtonComponent, DatePickerComponent],
  templateUrl: './advanced-filter.component.html',
  styleUrl: './advanced-filter.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AdvancedFilterComponent {
  // ── Inputs ────────────────────────────────
  /** Placeholder text for the search input. */
  readonly searchPlaceholder = input<string>('Search...');

  /** Extra filter fields shown in the advanced panel. */
  readonly fields = input<FilterField[]>([]);

  /** Whether to show the PDF export button. */
  readonly showExportPdf = input<boolean>(true);

  /** Whether to show the Excel export button. */
  readonly showExportExcel = input<boolean>(true);

  /** Whether to show the CSV export button. Opt-in: only lists whose service
   *  supports CSV export and bind (exportCsv) should enable it. */
  readonly showExportCsv = input<boolean>(false);

  /** Whether to show the Create button. */
  readonly showCreate = input<boolean>(true);

  /** Label for the Create button. */
  readonly createLabel = input<string>('New');

  // ── Outputs ───────────────────────────────
  readonly filtersChange = output<FilterCriteria>();
  readonly create = output<void>();
  readonly exportPdf = output<void>();
  readonly exportExcel = output<void>();
  readonly exportCsv = output<void>();

  // ── State (signals) ───────────────────────
  readonly search = signal('');
  readonly advancedOpen = signal(false);

  /** Upper bound for date-range filters: future dates make no sense for "created/updated" filtering. */
  readonly maxDate = new Date();

  /** Dynamic filter values stored by field key. */
  readonly filterValues = signal<Record<string, unknown>>({});

  /** Count of active advanced filters (excluding search). */
  readonly activeCount = computed(() => {
    const values = this.filterValues();
    const fields = this.fields();
    let count = 0;
    for (const field of fields) {
      const val = values[field.key];
      if (val === undefined || val === null) continue;
      if (Array.isArray(val) && val.length === 0) continue;
      if (typeof val === 'string' && val.trim() === '') continue;
      count++;
    }
    return count;
  });

  private debounce?: ReturnType<typeof setTimeout>;

  onSearchInput(value: string): void {
    this.search.set(value);
    clearTimeout(this.debounce);
    this.debounce = setTimeout(() => this.emit(), 300);
  }

  toggleAdvanced(): void {
    this.advancedOpen.update((v) => !v);
  }

  apply(): void {
    this.emit();
    this.advancedOpen.set(false);
  }

  clear(): void {
    this.search.set('');
    this.filterValues.set({});
    this.emit();
  }

  /** Update a single filter field value. */
  setFilterValue(key: string, value: unknown): void {
    this.filterValues.update((current) => ({
      ...current,
      [key]: value,
    }));
  }

  /** Get the current value for a filter field. */
  getFilterValue(key: string): unknown {
    return this.filterValues()[key];
  }

  /** Set value and immediately emit (for selects / datepickers). */
  onFieldChange(key: string, value: unknown): void {
    this.setFilterValue(key, value);
    this.emit();
  }

  emit(): void {
    this.filtersChange.emit({
      search: this.search().trim(),
      ...this.filterValues(),
    });
  }
}

<div class="filter-bar">
  <!-- LEFT: search + advanced toggle -->
  <div class="filter-bar__left">
    <div class="search-box">
      <svg class="search-box__icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
        <circle cx="11" cy="11" r="7" /><path d="m21 21-4.3-4.3" />
      </svg>
      <input
        class="search-box__input"
        type="text"
        [placeholder]="searchPlaceholder()"
        [value]="search()"
        (input)="onSearchInput($any($event.target).value)" />
      @if (search()) {
        <button class="search-box__clear" type="button" aria-label="Clear search" (click)="onSearchInput('')">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M18 6 6 18M6 6l12 12" /></svg>
        </button>
      }
    </div>

    <button class="btn btn--ghost filter-toggle" type="button" [class.active]="advancedOpen()" (click)="toggleAdvanced()">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M22 3H2l8 9.46V19l4 2v-8.54L22 3z" />
      </svg>
      <span>Filters</span>
      @if (activeCount() > 0) {
        <span class="filter-toggle__badge">{{ activeCount() }}</span>
      }
    </button>
  </div>

  <!-- RIGHT: actions -->
  <div class="filter-bar__actions">
    @if (showExportPdf()) {
      <button class="btn btn--ghost" type="button" (click)="exportPdf.emit()">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><path d="M14 2v6h6" /></svg>
        <span>PDF</span>
      </button>
    }
    @if (showExportExcel()) {
      <button class="btn btn--ghost" type="button" (click)="exportExcel.emit()">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><path d="M14 2v6h6M9 13l6 6M15 13l-6 6" /></svg>
        <span>Excel</span>
      </button>
    }
    @if (showExportCsv()) {
      <button class="btn btn--ghost" type="button" (click)="exportCsv.emit()">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><path d="M14 2v6h6M8 13h2M8 17h2M14 13h2M14 17h2" /></svg>
        <span>CSV</span>
      </button>
    }
    @if (showCreate()) {
      <app-animated-button
        [text]="createLabel()"
        variant="primary"
        icon="pi-plus"
        (onClick)="create.emit()" />
    }
  </div>

  <!-- ADVANCED PANEL -->
  @if (advancedOpen()) {
    <div class="filter-panel">
      @for (field of fields(); track field.key) {
        <div class="filter-field">
          <label>{{ field.label }}</label>

          @switch (field.type) {
            @case ('date-range') {
              <app-date-picker
                [ngModel]="getFilterValue(field.key)"
                (ngModelChange)="onFieldChange(field.key, $event)"
                selectionMode="range"
                valueFormat="date"
                [readonlyInput]="true"
                [maxDate]="maxDate"
                [showIcon]="false"
                [placeholder]="field.placeholder ?? 'Start — End'" />
            }
            @case ('select') {
              <p-select
                [options]="field.options ?? []"
                [ngModel]="getFilterValue(field.key)"
                (onChange)="onFieldChange(field.key, $event.value ?? $event)"
                optionLabel="label"
                optionValue="value"
                [placeholder]="field.placeholder ?? 'All'"
                [showClear]="true"
                styleClass="filter-select" />
            }
            @case ('trash') {
              <p-select
                [options]="[{ label: 'Active', value: 'active' }, { label: 'Deleted', value: 'deleted' }, { label: 'All', value: 'all' }]"
                [ngModel]="getFilterValue(field.key)"
                (onChange)="onFieldChange(field.key, $event.value ?? $event)"
                optionLabel="label"
                optionValue="value"
                [placeholder]="field.placeholder ?? 'All'"
                [showClear]="true"
                styleClass="filter-select" />
            }
            @case ('text') {
              <input
                type="text"
                class="filter-text-input"
                [placeholder]="field.placeholder ?? ''"
                [ngModel]="getFilterValue(field.key)"
                (ngModelChange)="setFilterValue(field.key, $event)" />
            }
          }
        </div>
      }

      <div class="filter-panel__actions">
        <button class="btn btn--ghost" type="button" (click)="clear()">Clear</button>
        <button class="btn btn--primary" type="button" (click)="apply()">Apply</button>
      </div>
    </div>
  }
</div>

// resources/js/common/data-table/AdvancedFilter.vue
<script setup lang="ts">
/**
 * Generic, domain-agnostic list toolbar: debounced search + collapsible advanced
 * panel (configurable select / date-range / text / trash fields) + export and
 * create actions. Emits a flat FilterCriteria the parent maps into its query
 * params. Ported from the GUIDE `app-advanced-filter`.
 *
 * Layer: common/ — imports volt/ only, never modules/ or Pages/.
 */
import { computed, onBeforeUnmount, ref } from 'vue';
import Button from '@/volt/Button.vue';
import Select from '@/volt/Select.vue';
import InputText from '@/volt/InputText.vue';
import DatePicker from '@/volt/DatePicker.vue';

export interface FilterOption {
    label: string;
    value: string;
}

export interface FilterField {
    key: string;
    label: string;
    type: 'select' | 'date-range' | 'text' | 'trash';
    options?: FilterOption[];
    placeholder?: string;
}

export interface FilterCriteria {
    search: string;
    [key: string]: unknown;
}

const props = withDefaults(
    defineProps<{
        searchPlaceholder?: string;
        fields?: FilterField[];
        showExportPdf?: boolean;
        showExportExcel?: boolean;
        showExportCsv?: boolean;
        showCreate?: boolean;
        createLabel?: string;
    }>(),
    {
        searchPlaceholder: 'Search…',
        fields: () => [],
        showExportPdf: true,
        showExportExcel: true,
        showExportCsv: false,
        showCreate: true,
        createLabel: 'New',
    },
);

const emit = defineEmits<{
    filtersChange: [criteria: FilterCriteria];
    create: [];
    exportPdf: [];
    exportExcel: [];
    exportCsv: [];
}>();

const TRASH_OPTIONS: FilterOption[] = [
    { label: 'Active', value: 'active' },
    { label: 'Deleted', value: 'deleted' },
    { label: 'All', value: 'all' },
];

/** Upper bound for date-range fields — future dates never apply to created/updated filters. */
const maxDate = new Date();

const search = ref<string>('');
const advancedOpen = ref<boolean>(false);
const filterValues = ref<Record<string, unknown>>({});

const activeCount = computed<number>(() => {
    let count = 0;
    for (const field of props.fields) {
        const val = filterValues.value[field.key];
        if (val === undefined || val === null) {
            continue;
        }
        if (Array.isArray(val) && val.length === 0) {
            continue;
        }
        if (typeof val === 'string' && val.trim() === '') {
            continue;
        }
        count++;
    }
    return count;
});

let debounceHandle: ReturnType<typeof setTimeout> | undefined;
onBeforeUnmount(() => clearTimeout(debounceHandle));

function emitCriteria(): void {
    emit('filtersChange', { search: search.value.trim(), ...filterValues.value });
}

function onSearchInput(value: string): void {
    search.value = value;
    clearTimeout(debounceHandle);
    debounceHandle = setTimeout(emitCriteria, 300);
}

function setFilterValue(key: string, value: unknown): void {
    filterValues.value = { ...filterValues.value, [key]: value };
}

function onFieldChange(key: string, value: unknown): void {
    setFilterValue(key, value);
    emitCriteria();
}

function getFilterValue(key: string): unknown {
    return filterValues.value[key];
}

function toggleAdvanced(): void {
    advancedOpen.value = !advancedOpen.value;
}

function apply(): void {
    emitCriteria();
    advancedOpen.value = false;
}

function clear(): void {
    search.value = '';
    filterValues.value = {};
    emitCriteria();
}
</script>

<template>
    <div class="filter-bar">
        <div class="filter-bar__left">
            <div class="search-box">
                <i class="pi pi-search search-box__icon" aria-hidden="true" />
                <input
                    class="search-box__input"
                    type="text"
                    :placeholder="searchPlaceholder"
                    :value="search"
                    aria-label="Search"
                    @input="onSearchInput(($event.target as HTMLInputElement).value)"
                />
                <button
                    v-if="search"
                    class="search-box__clear"
                    type="button"
                    aria-label="Clear search"
                    @click="onSearchInput('')"
                >
                    <i class="pi pi-times" aria-hidden="true" />
                </button>
            </div>

            <Button
                type="button"
                icon="pi pi-filter"
                :label="`Filters${activeCount > 0 ? ` (${activeCount})` : ''}`"
                :outlined="!advancedOpen"
                severity="secondary"
                aria-label="Toggle advanced filters"
                :aria-expanded="advancedOpen"
                @click="toggleAdvanced"
            />
        </div>

        <div class="filter-bar__actions">
            <Button
                v-if="showExportPdf"
                type="button"
                icon="pi pi-file-pdf"
                label="PDF"
                outlined
                severity="secondary"
                @click="emit('exportPdf')"
            />
            <Button
                v-if="showExportExcel"
                type="button"
                icon="pi pi-file-excel"
                label="Excel"
                outlined
                severity="secondary"
                @click="emit('exportExcel')"
            />
            <Button
                v-if="showExportCsv"
                type="button"
                icon="pi pi-file"
                label="CSV"
                outlined
                severity="secondary"
                @click="emit('exportCsv')"
            />
            <Button
                v-if="showCreate"
                type="button"
                icon="pi pi-plus"
                :label="createLabel"
                @click="emit('create')"
            />
        </div>

        <Transition name="panel">
            <div v-if="advancedOpen" class="filter-panel">
                <div v-for="field in fields" :key="field.key" class="filter-field">
                    <label :for="`filter-${field.key}`">{{ field.label }}</label>

                    <DatePicker
                        v-if="field.type === 'date-range'"
                        :input-id="`filter-${field.key}`"
                        :model-value="(getFilterValue(field.key) as Date[] | null | undefined)"
                        selection-mode="range"
                        :max-date="maxDate"
                        :manual-input="false"
                        :placeholder="field.placeholder ?? 'Start — End'"
                        fluid
                        @update:model-value="(v) => onFieldChange(field.key, v)"
                    />

                    <Select
                        v-else-if="field.type === 'select' || field.type === 'trash'"
                        :input-id="`filter-${field.key}`"
                        :model-value="getFilterValue(field.key)"
                        :options="field.type === 'trash' ? TRASH_OPTIONS : (field.options ?? [])"
                        option-label="label"
                        option-value="value"
                        :placeholder="field.placeholder ?? 'All'"
                        show-clear
                        fluid
                        @update:model-value="(v) => onFieldChange(field.key, v)"
                    />

                    <InputText
                        v-else
                        :id="`filter-${field.key}`"
                        :model-value="(getFilterValue(field.key) as string | undefined)"
                        :placeholder="field.placeholder ?? ''"
                        fluid
                        @update:model-value="(v) => setFilterValue(field.key, v)"
                    />
                </div>

                <div class="filter-panel__actions">
                    <Button type="button" label="Clear" text severity="secondary" @click="clear" />
                    <Button type="button" label="Apply" @click="apply" />
                </div>
            </div>
        </Transition>
    </div>
</template>

<style scoped>
.filter-bar {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.75rem;
    padding: 1rem;
    background: color-mix(in srgb, var(--bg-surface) 55%, transparent);
    backdrop-filter: blur(16px);
    -webkit-backdrop-filter: blur(16px);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-lg);
}

.filter-bar__left {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    flex: 1;
    min-width: 240px;
}

.filter-bar__actions {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-left: auto;
}

.search-box {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    flex: 1;
    max-width: 360px;
    height: 40px;
    padding: 0 0.75rem;
    background: var(--input-bg);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-md);
    transition: border-color var(--transition), box-shadow var(--transition);
}

.search-box:focus-within {
    border-color: color-mix(in srgb, var(--accent-primary) 55%, transparent);
    box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent-primary) 14%, transparent);
}

.search-box__icon {
    font-size: 0.9rem;
    color: var(--text-muted);
    flex-shrink: 0;
}

.search-box__input {
    flex: 1;
    min-width: 0;
    height: 100%;
    background: transparent;
    border: none;
    outline: none;
    color: var(--text-primary);
    font-size: 0.875rem;
}

.search-box__input::placeholder {
    color: var(--text-muted);
}

.search-box__clear {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 20px;
    border: none;
    background: transparent;
    color: var(--text-muted);
    cursor: pointer;
    flex-shrink: 0;
}

.search-box__clear:hover {
    color: var(--text-primary);
}

.filter-panel {
    flex-basis: 100%;
    display: flex;
    flex-wrap: wrap;
    align-items: flex-end;
    gap: 1rem;
    margin-top: 0.5rem;
    padding-top: 1rem;
    border-top: 1px solid var(--border-default);
}

.filter-field {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    min-width: 220px;
}

.filter-field label {
    font-size: 0.75rem;
    font-weight: 500;
    color: var(--text-secondary);
}

.filter-panel__actions {
    display: flex;
    gap: 0.5rem;
    margin-left: auto;
}

.panel-enter-active,
.panel-leave-active {
    transition: opacity var(--transition), transform var(--transition);
}

.panel-enter-from,
.panel-leave-to {
    opacity: 0;
    transform: translateY(-6px);
}

@media (max-width: 768px) {
    .filter-bar__left {
        width: 100%;
        flex-basis: 100%;
    }

    .search-box {
        max-width: none;
    }

    .filter-bar__actions {
        width: 100%;
        margin-left: 0;
    }

    .filter-field {
        min-width: 100%;
    }

    .filter-panel__actions {
        width: 100%;
        margin-left: 0;
    }
}
</style>
